Repository AaronStahley/SER401-BLSI, pull requests merged in 2019-02, with the labels that each got.

#29 Sprint7/us204/aaron
  assets/images/recomendationIcon.png
  src/common/Colors.js
  src/common/Images.js
  src/components/__tests__/ui/__snapshots__/NumberField.test.js.snap
  src/components/__tests__/ui/__snapshots__/TextField.test.js.snap
  src/components/question/CheckBox.js
  src/components/question/Question.js
  src/components/question/QuestionContainer.js
  src/components/question/QuestionInput.js
  src/components/recommendation/Recommendation.js
  src/components/recommendation/RecommendationContainer.js
  src/components/ui/NumberField.js
  src/screens/ConversationScreen.js
Labels: enhancement

#37 Sprint8/us252/taylor
  package.json
  src/components/ui/RefreshButton.js
  src/screens/AlgDescriptionScreen.js
  src/screens/ConversationScreen.js
  src/screens/HomeScreen.js
  src/services/fetchAlgorithm.js
  src/services/fetchAlgorithms.js
Labels: bug-fix

#39 Task#283 - Found a way to get the search bar to render onPress.
  src/components/ui/RefreshButton.js
  src/components/ui/SearchButton.js
  src/screens/HomeScreen.js
Labels: bug-fix

#41 Sprint8/us254/aaron
  assets/db/database.db
  src/model/Algorithm.js
  src/screens/HomeScreen.js
Labels: bug-fix, enhancement

#43 Sprint8/us254/aaron
  src/common/Colors.js
  src/components/navigation/MainTabNavigator.js
  src/components/ui/Card.js
  src/components/ui/FavoritesIcon.js
  src/screens/HomeScreen.js
Labels: bug-fix, enhancement
