Repository AaronStahley/SER401-BLSI, pull requests merged in 2019-04, with the labels that each got.

#78 Algo update
  assets/db/database.db
  assets/db/database_OLD.db
  src/components/app/home/AlgDescriptionScreen.js
Labels: bug-fix, enhancement

#83 Sprint10/us334/cristina
  package.json
  src/components/app/conversation/RecommendationScreen.js
  src/components/app/conversation/question/QuestionContainer.js
  src/components/app/conversation/recommendation/RecommendationContainer.js
  src/components/app/home/AlgDescriptionScreen.js
  src/components/app/home/AlgorithmListItem.js
  src/components/app/home/HomeComponent.js
  src/components/ui/Card.js
Labels: bug-fix, enhancement

#85 Sprint10/us334/conrad
  app.json
  assets/images/PCH_APP_LOGO-v2-red-bg-square.png
  assets/images/PCH_APP_LOGO-v2-red-bg.png
  assets/images/PCH_APP_LOGO-v2-red-lettering-bg.png
  assets/images/PCH_APP_LOGO-v2-red-lettering-center-bg.png
  assets/images/PCH_APP_LOGO-v2-white-bg-square.png
  assets/images/PCH_APP_LOGO-v2-white-bg.png
  assets/images/PCH_APP_LOGO-v2-white-lettering-bg.png
  assets/images/PCH_APP_LOGO-v2-white-lettering-center-bg-trans.png
  assets/images/PCH_APP_LOGO-v2-white-lettering-center-bg.png
  assets/images/PHOTOSHOP_MASTER_FILES/PCH_APP_LOGO.psd
  assets/images/PHOTOSHOP_MASTER_FILES/PCH_APP_LOGO_LETTERING_ONLY.psd
  assets/images/PHOTOSHOP_MASTER_FILES/PCH_APP_LOGO_SQUARE.psd
  assets/images/PHOTOSHOP_MASTER_FILES/SCREENSHOTS.psd
  assets/images/PHOTOSHOP_MASTER_FILES/SCREENSHOTS_PRESENTATION.psd
  assets/images/PHOTOSHOP_MASTER_FILES/SPLASH_SCREEN.psd
  assets/images/pch-splash-v2-red-bg.png
  assets/images/pch-splash-v2-white-bg.png
  src/App.js
  src/components/app/conversation/RecommendationScreen.js
  src/components/navigation/MainTabNavigator.js
Labels: enhancement

#80 updated db with version number table
  assets/db/database.db
Labels: enhancement

#81 Database version system in place
  app.json
  assets/db/database.db
  src/App.js
Labels: bug-fix, enhancement

#86 Db/update
  app.json
  assets/db/database.db
Labels: bug-fix

#87 Removed invalid prop on recommendation screen
  src/components/app/conversation/RecommendationScreen.js
Labels: bug-fix

#91 Added algorithm update
  app.json
  assets/db/database.db
  src/common/Environment.js
Labels: enhancement
