Repository AaronStahley/SER401-BLSI, pull requests merged in 2019-03, with the labels that each got.

#46 Sprint8/us254/aaron
  assets/db/database.db
  src/common/Colors.js
  src/components/navigation/MainTabNavigator.js
  src/components/ui/AlertBox.js
  src/components/ui/Button.js
  src/components/ui/Card.js
  src/components/ui/FavoritesIcon.js
  src/components/ui/RefreshAllButton.js
  src/components/ui/RefreshButton.js
  src/components/ui/SearchButton.js
  src/model/Algorithm.js
  src/model/Question.js
  src/model/Recommendation.js
  src/model/State.js
  src/model/StateQuestion.js
  src/model/StateRecommendation.js
  src/screens/AlgDescriptionScreen.js
  src/screens/HomeScreen.js
  src/services/fetchAlgorithms.js
  src/store/AbstractStore.js
  src/store/QuestionStore.js
  src/store/RecommendationStore.js
  src/store/RootStore.js
  src/store/StateQuestionStore.js
  src/store/StateRecommendationStore.js
  src/store/StateStore.js
  src/store/UpdateStore.js
Labels: bug-fix, enhancement

#51 Sprint8/us253 cristina
  src/components/ui/Card.js
  src/screens/AlgDescriptionScreen.js
  src/screens/HomeScreen.js
  src/screens/RecommendationScreen.js
Labels: bug-fix

#53 Sprint break/us290/taylor
  assets/db/database.db
  assets/db/database_empty.db
  assets/db/database_init.db
  package.json
  src/App.js
  src/common/Transporter.js
  src/components/question/QuestionContainer.js
  src/components/question/QuestionInput.js
  src/components/recommendation/Recommendation.js
  src/components/recommendation/RecommendationContainer.js
  src/components/state/StateContainer.js
  src/components/ui/RefreshAllButton.js
  src/components/ui/RefreshButton.js
  src/model/Update.js
  src/screens/AlgDescriptionScreen.js
  src/screens/HomeScreen.js
  src/screens/RecommendationScreen.js
  src/services/fetchAlgorithms.js
  src/store/AbstractStore.js
  src/store/QuestionAnswerStore.js
  src/store/QuestionStore.js
  src/store/RecommendationStore.js
  src/store/StateQuestionStore.js
  src/store/StateRecommendationStore.js
  src/store/StateStore.js
  src/store/UpdateStore.js
Labels: bug-fix, enhancement

#58 Fix for issue #57, and added loading animation for convo screen.
  src/screens/ConversationScreen.js
  src/store/AbstractStore.js
Labels: bug-fix, enhancement

#59 Sprint9/us298/aaron
  package.json
  src/components/__tests__/ui/__snapshots__/ProceedButton.test.js.snap
  src/components/navigation/EmailButton.js
  src/components/navigation/MainTabNavigator.js
  src/components/state/NextStateContainer.js
  src/components/state/StateContainer.js
  src/components/ui/EmailTextField.js
  src/components/ui/ProceedButton.js
  src/model/State.js
  src/screens/AlgDescriptionScreen.js
  src/screens/ConversationScreen.js
  src/screens/DischargeScreen.js
  src/store/AbstractStore.js
Labels: enhancement

#60 US298
  package.json
  src/common/Colors.js
  src/components/__tests__/ui/__snapshots__/ProceedButton.test.js.snap
  src/components/navigation/EmailButton.js
  src/components/navigation/MainTabNavigator.js
  src/components/recommendation/RecommendationContainer.js
  src/components/state/NextStateContainer.js
  src/components/state/StateContainer.js
  src/components/ui/EmailTextField.js
  src/components/ui/ProceedButton.js
  src/model/State.js
  src/screens/AlgDescriptionScreen.js
  src/screens/ConversationScreen.js
  src/screens/DischargeScreen.js
Labels: enhancement

#66 Fixed some bugs for release.
  app.json
  assets/db/database.db
  src/App.js
  src/components/app/home/HomeComponent.js
Labels: bug-fix

#67 TASK#336 - Fixed nav bar covering android notification bar.
  src/App.js
  src/components/app/conversation/DischargeScreen.js
  src/components/app/home/HomeComponent.js
  src/components/navigation/MainTabNavigator.js
Labels: bug-fix

#68 TASK#357
  src/store/QuestionAnswerStore.js
Labels: bug-fix

#71 Updated algorithm
  assets/db/database.db
  assets/db/database_OLD.db
Labels: enhancement

#73 db V0.04
  assets/db/database.db
Labels: enhancement
